##-----------------------------------------------------#
# Training parameters
NUM_EPOCHS: 100
BATCH_SIZE: 128
LEARNING_RATE: 0.0001
DROP_OUT: 0.10
TEST_SIZE: 0.15
VALID_SIZE: 0.15
NORMALIZE_WEIGHT: True

##-----------------------------------------------------#
# Data Parameters
seq_length: 4
predict_length: 0
n_actions: 3
n_classes: 23
frame_skip: 4
number_workers: 8

##-----------------------------------------------------#
# Base Policy parameters
obs_size: 1

##-----------------------------------------------------#
# CARNet Parameters
latent_size: 128
rnn_input_size: 128
hidden_size: 128
layers_encoder: null
layers_decoder: null
gru_input_size: 2
gru_hidden_size: 64
n_waypoints: 2

##-----------------------------------------------------#
# Other parameters
image_size: [1, 256, 256]
crop: False
crop_image_resize: [1, 78, 128]
image_resize: [1, 256, 256]
alpha: 0.75
beta: 0.1
action_processing_id: 6 # 1, 2, 3, 4, 5, 6
use_scheduler: True
normalize_kalman: True
clip_kalman: True
max_position: 400
max_velocity: 20

##-----------------------------------------------------#
# Data splitting scheme
available_weathers: [
    'MidRainSunset', # Done
    'ClearNoon', # Done
    'SoftRainNoon', # Done
    'HardRainNoon', # Testing (Done)
    'ClearSunset', # Testing (not done)
    'SoftRainSunset', # Done
    'HardRainSunset', # Testing
  ]
navigation_types: ['navigation'] # 'straight', , 'navigation'
data_split:
  training:
    town: ['Town01']
    season: ['ClearNoon', 'SoftRainNoon', 'SoftRainSunset', 'MidRainSunset']
    behavior: ['cautious']
  validation:
    town: ['Town01']
    season: ['HardRainSunset']
    behavior: ['cautious']
  testing:
    town: []
    season: []
    behavior: []

##-----------------------------------------------------#
# Path(s)
slurm: True
# raw_data_path: '/home/hemanth/Desktop/carla-data/Town01_NAVIGATION/'
raw_data_path: '../carla-data/Town01_NAVIGATION/'
# raw_data_path: '/Users/hemanth/Desktop/carla_data/'
logs_path: 'logs/'
train_data_path: 'data/raw/train'
val_data_path: 'data/raw/validation'
test_data_path: 'data/raw/test'

check_point_path: null #'logs/2022-10-25/AUTOENCODER/last.ckpt'

##-----------------------------------------------------#
# Benchmark config
benchmark_config:
  benchmark: 'corl2017'
  city_name: 'Town01'
  log_name: local_test
  continue_experiment: False
  host: null
  port: null

##-----------------------------------------------------#
# Carla server parameters
carla_server:
  host: 'localhost'
  retries_on_error: 25
  resolution_x: 600
  resolution_y: 600
  quality_level: 'Low'
  enable_map_assets: True
  enable_rendering: True
  show_display: True
  carla_path: '/home/hemanth/Carla/CARLA_0.9.11'

pytorch_seed: 1337
